/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfileVisibility = IDL.Variant({
  'privateVisibility' : IDL.Null,
  'publicVisibility' : IDL.Null,
});
export const SerializableUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'currentProjects' : IDL.Text,
  'programmingLanguages' : IDL.Text,
  'displayName' : IDL.Text,
  'activityInterests' : IDL.Text,
  'socialLinks' : IDL.Vec(IDL.Text),
  'number' : IDL.Text,
  'visibility' : ProfileVisibility,
  'skills' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const PublicProfile = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : SerializableUserProfile,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteChatMessage' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(SerializableUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getMemberDirectory' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SerializableUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([SerializableUserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfileVisibility = IDL.Variant({
    'privateVisibility' : IDL.Null,
    'publicVisibility' : IDL.Null,
  });
  const SerializableUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'currentProjects' : IDL.Text,
    'programmingLanguages' : IDL.Text,
    'displayName' : IDL.Text,
    'activityInterests' : IDL.Text,
    'socialLinks' : IDL.Vec(IDL.Text),
    'number' : IDL.Text,
    'visibility' : ProfileVisibility,
    'skills' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const PublicProfile = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : SerializableUserProfile,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteChatMessage' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(SerializableUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getMemberDirectory' : IDL.Func([], [IDL.Vec(PublicProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SerializableUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([SerializableUserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };