/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export type ProfileVisibility = { 'privateVisibility' : null } |
  { 'publicVisibility' : null };
export interface PublicProfile {
  'principal' : Principal,
  'isVerified' : boolean,
  'profile' : SerializableUserProfile,
}
export interface SerializableUserProfile {
  'bio' : string,
  'currentProjects' : string,
  'programmingLanguages' : string,
  'displayName' : string,
  'activityInterests' : string,
  'socialLinks' : Array<string>,
  'number' : string,
  'visibility' : ProfileVisibility,
  'skills' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatMessage' : ActorMethod<[string], bigint>,
  'deleteChatMessage' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [SerializableUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getMemberDirectory' : ActorMethod<[], Array<PublicProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [SerializableUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserVerified' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[SerializableUserProfile], undefined>,
  'toggleVerifiedBadge' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];